server:
  address: 
  port: ${PORT:8081}

spring:
  main:
    allow-bean-definition-overriding: true
    
  application:
    name: product-api
     
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-db
    username: admin
    password: admin123
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql
  
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
    
app-config:
  services:
    sales: http://${SALES_HOST:localhost}:${SALES_PORT:8082}
    
  secrets:
    api-secret: ${API_SECRET:RWwgcHVlYmxvIHVuaWRvIGphbWFzIHNlcmEgdmVuY2lkbw==}
    
  rabbit:
    exchange:
      product: product.topic
      
    routingKey:
      product-stock: product-stock-update.routingKey
      sales-confirmation: sales-confirmation.routingKey
    
    queue:
      product-stock: product-stock-update.queue
      sales-confirmation: sales-confirmation.queue
      
      
        